### ISSUE TITLE
Broken URL in the Flatpak manifest

### ISSUE THREAD

**Issue by guihkx** [flathub/com.warlordsoftwares.youtube-downloader-4ktube#1]
The following URL doesn't exist:

https://github.com/flathub/com.warlordsoftwares.youtube-downloader-4ktube/blob/5c43991d760dd9d65ec3ac68520e7bcc509dfa7f/com.warlordsoftwares.youtube-downloader-4ktube.yml#L70-L73

In fact, the entire repo (https://github.com/rishabh3354/FLATPAK_4KTUBE) doesn't exist anymore.

**Comment by hfiguiere** [comment]
Nor does the other from the same developers

**Comment by hfiguiere** [comment]
cc @rishabh3354

**Comment by rishabh3354** [comment]
Resolved.

**Comment by guihkx** [comment]
@rishabh3354 Thank you.

Just a heads up: It seems like the entire source code of the app is available in the repository as well. I'm not sure if that's intentional, given that the app is proprietary.

So you might want to rethink your distribution strategy.
